[workspace]
members = ["examples/*"]

[package]
name = "option_chain_tool"
version = "0.10.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]


[workspace.lints.rust]
dead_code = "allow"
unused_imports = "allow"
unused_variables = "allow"
unused = "allow"
unused_mut = "allow"
